spring:
  application:
    name: webservice
  thymeleaf:
    suffix: .html
    cache: false
    mode: HTML
    encoding: UTF-8
    content-type: text/html
    prefix: classpath:/templates/
    check-template-location: true
